### ISSUE TITLE
TypeError: unsupported format string passed to module.__format__

### ISSUE THREAD

**Issue by Bakhtafarid1** [glad-tidings/MajorBot#3]
![pic](https://github.com/user-attachments/assets/b022710c-0eb5-44f8-ab32-0df959057569)

**Comment by glad-tidings** [comment]
fix this problem
pls use the new code and be sure to view readme

**Comment by Bakhtafarid1** [comment]
> fix this problem pls use the new code and be sure to view readme
AttributeError: 'dict' object has no attribute 'title'
![Capture](https://github.com/user-attachments/assets/52ba4be5-49a9-4e37-8bcb-0d2f286ec3aa)

**Comment by glad-tidings** [comment]
try new code

**Comment by Bakhtafarid1** [comment]
> try new code

Thank you, it works
