### ISSUE TITLE
SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by primushkodenis** [glad-tidings/MajorBot#7]
File "/home/MajorBot/Major.py", line 184
    print(f"[{'{0:%Y-%m-%d %H:%M:%S}'.format(datetime.now())}] [Major] [{query.name}] synced successfully. B<{sync["rating"]}>")
                                                                                                                    ^^^^^^
SyntaxError: f-string: unmatched '['

**Comment by primushkodenis** [comment]
print(f"[{'{0:%Y-%m-%d %H:%M:%S}'.format(datetime.now())}] [Major] [{query.name}] synced successfully. B<{sync['rating']}>")

replace " with '

**Comment by Kravt48** [comment]
> print(f"[{'{0:%Y-%m-%d %H:%M:%S}'.format(datetime.now())}] [Основной] [{query.name}] успешно синхронизирован. B<{sync['rating']}>")
> 
> заменить " на '

Hi, thanks for the instructions, but that didn't help. As soon as you change this line, an error appears on another line and so on ad infinitum

**Comment by PTPL-LKO** [comment]
same error

**Comment by glad-tidings** [comment]
This is a major server problem, please be patient
